/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eko Putro Fitrianto
 */

public class Form_Koneksi extends javax.swing.JFrame {
    public myEchoClient clientku;
    private UI_client ui_client;
    public UI_clientAi clientAi;
    
    private String nama;
    private InetAddress ip;
    private Integer port;
    
    /**
     * Creates new form Form_Koneksi
     */
    public Form_Koneksi() {
        initComponents();
    }
    
    public String getName()
    {
        return this.nama;
    }
    
    public void setName(String name)
    {
        this.nama = name;
    }
    
    public InetAddress getIP()
    {
        return this.ip;
    }
    
    public void setIP(InetAddress ip)
    {
        this.ip = ip;
    }
    
    public Integer getPort()
    {
        return this.port;
    }
    
    public void setPort(Integer port)
    {
        this.port = port;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_IP = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_connect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mode1 = new javax.swing.JRadioButton();
        mode2 = new javax.swing.JRadioButton();

        jLabel7.setText("MODE BERMAIN");

        jLabel8.setText("MODE BERMAIN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Koneksi Client");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_IP.setText("localhost");
        txt_IP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IPActionPerformed(evt);
            }
        });

        txt_port.setText("1234");
        txt_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_portActionPerformed(evt);
            }
        });

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        jLabel4.setText("USERNAME");

        jLabel5.setText("PORT");

        jLabel6.setText("IP HOST");

        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });

        jLabel2.setText("MODE BERMAIN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Koneksi Client");

        buttonGroup1.add(mode1);
        mode1.setText("Single Player");
        mode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(mode2);
        mode2.setText("Dual Player");
        mode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mode2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(mode1)
                        .addGap(18, 18, 18)
                        .addComponent(mode2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_IP, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txt_port)
                            .addComponent(txt_username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btn_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(btn_connect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mode1)
                    .addComponent(mode2))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IPActionPerformed

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        String message = "null";
        
        /*play single*/
        if(this.mode1.isSelected()) { 
            if(txt_IP.getText().equals("") || txt_port.getText().equals("") || txt_username.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Complete the blank Form first");
                System.out.println("testes");
            } //else if (txt_IP.getText().equals("10.151.43.92")) {
              //  JOptionPane.showMessageDialog(null,"Your IP incorrect!\nIf you play with single player, set your IP with 'loclahost'.");
            //}
            else    {
                try{
                    this.btn_connect.setEnabled(false);

                    this.setName(txt_username.getText());
                    this.setIP(InetAddress.getByName(txt_IP.getText()));
                    this.setPort(Integer.parseInt(txt_port.getText()));
                    System.out.println("tes :" +this.getName() + this.getIP() + this.getPort());
                    ui_client = new UI_client(this, this.getName(),this.getIP(), this.getPort());
                                        
                    this.hide();
                    this.ui_client.show();

                    clientAi = new UI_clientAi(this.getIP());
                    clientAi.setVisible(true);
                    clientAi.main();
                }
                
                catch(NullPointerException n)
                {

                } catch (UnknownHostException ex) {
                    Logger.getLogger(Form_Koneksi.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
        } else if(this.mode2.isSelected()) { /*play double*/
            if(txt_IP.getText().equals("") || txt_port.getText().equals("") || txt_username.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Complete the blank Form first");
            else    {
                try{
                    this.btn_connect.setEnabled(false);

                    this.setName(txt_username.getText());
                    this.setIP(InetAddress.getByName(txt_IP.getText()));
                    this.setPort(Integer.parseInt(txt_port.getText()));
                    System.out.println("tes :" +this.getName() + this.getIP() + this.getPort());
                    ui_client = new UI_client(this, this.getName(),this.getIP(), this.getPort());
                    this.hide();
                    this.ui_client.show();
                }
                catch(NullPointerException n)
                {

                } catch (UnknownHostException ex) {
                    Logger.getLogger(Form_Koneksi.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
        }  else  {
            JOptionPane.showMessageDialog(null,"Complete the blank Form first");
        }
    }//GEN-LAST:event_btn_connectActionPerformed

    private void mode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mode1ActionPerformed

    private void mode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mode2ActionPerformed

    private void txt_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_portActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Koneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Koneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Koneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Koneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Koneksi().setVisible(true);
            }
        });
    }
    
//    void writelog(String s)
//    {
//        this.txt_log.append(s + "\n");
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton mode1;
    private javax.swing.JRadioButton mode2;
    private javax.swing.JTextField txt_IP;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
