/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

/**
 *
 * @author Fandazky23
 */

import java.awt.Color;
import java.io.*;
import java.net.InetAddress;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;

/*ambil tanggal*/
import java.util.Date; 
import java.text.DateFormat; 
import java.text.SimpleDateFormat; 

import java.io.BufferedWriter;
import java.io.FileWriter;


public class UI_client extends javax.swing.JFrame {
    int angka_tampil=0;
    public String[] input = new String[26];
    //socketClient myClient;
    public int temp;
    public myEchoClient clientku;
    
    DataInputStream in = null;
    DataOutputStream out = null;
    public String nama;
    public String terima;
    public int[] aray_isi = new int[27];
    public Form_Koneksi form_koneksi;
    
    /**
     * Creates new form UI
     */
    public UI_client(Form_Koneksi koneksi, String nama, InetAddress ip, Integer port) {
        initComponents();
        for(int i=0; i<25; i++) {
            input[i] = "x";
            aray_isi[i] =0;
        }
        aray_isi[25] = 0;
        form_koneksi = koneksi;
        this.nama = form_koneksi.getName();
        clientku = new myEchoClient(this, ip, port, nama);
        System.out.println("teslagi" + this.nama);
        clientku.makeClient();
        System.out.println(nama +" "+form_koneksi.getIP()+" "+form_koneksi.getPort());  
    }
    
    public UI_client(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        sepuluh = new javax.swing.JButton();
        sebelas = new javax.swing.JButton();
        duabelas = new javax.swing.JButton();
        tigabelas = new javax.swing.JButton();
        empatbelas = new javax.swing.JButton();
        limabelas = new javax.swing.JButton();
        enambelas = new javax.swing.JButton();
        tujuhbelas = new javax.swing.JButton();
        delapanbelas = new javax.swing.JButton();
        sembilanbelas = new javax.swing.JButton();
        duapuluh = new javax.swing.JButton();
        duapuluhsatu = new javax.swing.JButton();
        duapuluhdua = new javax.swing.JButton();
        duapuluhtiga = new javax.swing.JButton();
        duapuluhempat = new javax.swing.JButton();
        duapuluhlima = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_log = new javax.swing.JTextArea();
        textbox_send = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        text_username = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnCetakLog = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        satu.setText("?");
        satu.setPreferredSize(new java.awt.Dimension(45, 45));
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });

        dua.setText("?");
        dua.setPreferredSize(new java.awt.Dimension(45, 45));
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });

        lima.setText("?");
        lima.setPreferredSize(new java.awt.Dimension(45, 45));
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });

        tiga.setText("?");
        tiga.setPreferredSize(new java.awt.Dimension(45, 45));
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });

        empat.setText("?");
        empat.setPreferredSize(new java.awt.Dimension(45, 45));
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });

        enam.setText("?");
        enam.setPreferredSize(new java.awt.Dimension(45, 45));
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });

        tujuh.setText("?");
        tujuh.setPreferredSize(new java.awt.Dimension(45, 45));
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });

        delapan.setText("?");
        delapan.setPreferredSize(new java.awt.Dimension(45, 45));
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });

        sembilan.setText("?");
        sembilan.setPreferredSize(new java.awt.Dimension(45, 45));
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });

        sepuluh.setText("?");
        sepuluh.setPreferredSize(new java.awt.Dimension(45, 45));
        sepuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepuluhActionPerformed(evt);
            }
        });

        sebelas.setText("?");
        sebelas.setPreferredSize(new java.awt.Dimension(45, 45));
        sebelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebelasActionPerformed(evt);
            }
        });

        duabelas.setText("?");
        duabelas.setPreferredSize(new java.awt.Dimension(45, 45));
        duabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duabelasActionPerformed(evt);
            }
        });

        tigabelas.setText("?");
        tigabelas.setPreferredSize(new java.awt.Dimension(45, 45));
        tigabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigabelasActionPerformed(evt);
            }
        });

        empatbelas.setText("?");
        empatbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        empatbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatbelasActionPerformed(evt);
            }
        });

        limabelas.setText("?");
        limabelas.setPreferredSize(new java.awt.Dimension(45, 45));
        limabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limabelasActionPerformed(evt);
            }
        });

        enambelas.setText("?");
        enambelas.setPreferredSize(new java.awt.Dimension(45, 45));
        enambelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enambelasActionPerformed(evt);
            }
        });

        tujuhbelas.setText("?");
        tujuhbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        tujuhbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhbelasActionPerformed(evt);
            }
        });

        delapanbelas.setText("?");
        delapanbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        delapanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanbelasActionPerformed(evt);
            }
        });

        sembilanbelas.setText("?");
        sembilanbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        sembilanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanbelasActionPerformed(evt);
            }
        });

        duapuluh.setText("?");
        duapuluh.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhActionPerformed(evt);
            }
        });

        duapuluhsatu.setText("?");
        duapuluhsatu.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhsatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhsatuActionPerformed(evt);
            }
        });

        duapuluhdua.setText("?");
        duapuluhdua.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhduaActionPerformed(evt);
            }
        });

        duapuluhtiga.setText("?");
        duapuluhtiga.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhtiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhtigaActionPerformed(evt);
            }
        });

        duapuluhempat.setText("?");
        duapuluhempat.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhempatActionPerformed(evt);
            }
        });

        duapuluhlima.setText("?");
        duapuluhlima.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhlimaActionPerformed(evt);
            }
        });

        txt_log.setColumns(20);
        txt_log.setRows(5);
        jScrollPane1.setViewportView(txt_log);

        textbox_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_sendActionPerformed(evt);
            }
        });

        btn_send.setText("Tebak");
        btn_send.setEnabled(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_play.setText("Play");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        jButton1.setText("Random");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Bingo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("username :");

        text_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_username.setText("username");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnCetakLog.setText("Cetak Log");
        btnCetakLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sebelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(duabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(tigabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empatbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enambelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tujuhbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(delapanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sembilanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(duapuluhsatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duapuluhdua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(8, 8, 8)
                                .addComponent(duapuluhtiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_play, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(duapuluhempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(limabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duapuluh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duapuluhlima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sepuluh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(text_username))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textbox_send, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetakLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(278, 278, 278))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(sepuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sebelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tigabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(empatbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(enambelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tujuhbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(delapanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sembilanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(duapuluhsatu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duapuluhdua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duapuluhtiga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duapuluhempat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(limabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duapuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duapuluhlima, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(text_username)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textbox_send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetakLog, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        String values = JOptionPane.showInputDialog("Masukkan nilai");

        if(values == null || values.equalsIgnoreCase("")) {
            input[0] = "x";
        }
        else {
            input[0] = values;
            if(cek_sama(values)==true) {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                satu.setText("?");
                //System.out.println(values);
            } else if(Integer.parseInt(values) > 30) {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            } else {   
                satu.setText(values);
                satu.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_satuActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null||values.equalsIgnoreCase("")) {
            input[5] = "x";
        } else {
            input[5] = values;
            if(cek_sama(values)==true) {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                enam.setText("?");
                //System.out.println(values);
            } else if(Integer.parseInt(values) > 30) {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            } else {   
                enam.setText(values);
                enam.setBackground(Color.green);
            }
        }  
    }//GEN-LAST:event_enamActionPerformed

    private void sebelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase("")) {
            input[10] = "x";
        } else {
            input[10] = values;
            if(cek_sama(values)==true) {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                sebelas.setText("?");
                //System.out.println(values);
            } else if(Integer.parseInt(values) > 30) {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            } else {   
                sebelas.setText(values);
                sebelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_sebelasActionPerformed

    private void enambelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enambelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[15] = "x";
        }
        else
        {
            input[15] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                enambelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                enambelas.setText(values);
                enambelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_enambelasActionPerformed

    private void duapuluhsatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhsatuActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[20] = "x";
        }
        else
        {
            input[20] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duapuluhsatu.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                duapuluhsatu.setText(values);
                duapuluhsatu.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duapuluhsatuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed

        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[1] = "x";
        }
        else
        {
            input[1] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                dua.setText("?");
                //System.out.println(values);
            }
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                dua.setText(values);
                dua.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed

        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[2] = "x";
        }
        else
        {
            input[2] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                tiga.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                tiga.setText(values);
                tiga.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[3] = "x";
        }
        else
        {
            input[3] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                empat.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                empat.setText(values);
                empat.setBackground(Color.green);
            }
        }        

    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[4] = "x";
        }
        else
        {
            input[4] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                lima.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                lima.setText(values);
                lima.setBackground(Color.green);
            }
        }        

    }//GEN-LAST:event_limaActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[6] = "x";
        }
        else
        {
            input[6] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                tujuh.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                tujuh.setText(values);
                tujuh.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[7] = "x";
        }
        else
        {
            input[7] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                delapan.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                delapan.setText(values);
                delapan.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[8] = "x";
        }
        else
        {
            input[8] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                sembilan.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                sembilan.setText(values);
                sembilan.setBackground(Color.green);
            }
        } 
    }//GEN-LAST:event_sembilanActionPerformed

    private void sepuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepuluhActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[9] = "x";
        }
        else
        {
            input[9] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                sepuluh.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                sepuluh.setText(values);
                sepuluh.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_sepuluhActionPerformed

    private void duabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duabelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[11] = "x";
        }
        else
        {
            input[11] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duabelas.setText("?");
                //System.out.println(values);
            }
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
              duabelas.setText(values);
               duabelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duabelasActionPerformed

    private void tigabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigabelasActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[12] = "x";
        }
        else
        {
            input[12] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                tigabelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                tigabelas.setText(values);
                tigabelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_tigabelasActionPerformed

    private void empatbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatbelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[13] = "x";
        }
        else
        {
            input[13] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                empatbelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                empatbelas.setText(values);
                empatbelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_empatbelasActionPerformed

    private void limabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limabelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[14] = "x";
        }
        else
        {
            input[14] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                limabelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                limabelas.setText(values);
                limabelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_limabelasActionPerformed

    private void tujuhbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhbelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[16] = "x";
        }
        else
        {
            input[16] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                tujuhbelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                tujuhbelas.setText(values);
                tujuhbelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_tujuhbelasActionPerformed

    private void delapanbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanbelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[17] = "x";
        }
        else
        {
            input[17] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                delapanbelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                delapanbelas.setText(values);
                delapanbelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_delapanbelasActionPerformed

    private void sembilanbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanbelasActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[18] = "x";
        }
        else
        {
            input[18] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                sembilanbelas.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                sembilanbelas.setText(values);
                sembilanbelas.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_sembilanbelasActionPerformed

    private void duapuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[19] = "x";
        }
        else
        {
            input[19] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duapuluh.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                duapuluh.setText(values);
                duapuluh.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duapuluhActionPerformed

    private void duapuluhduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhduaActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[21] = "x";
        }
        else
        {
            input[21] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duapuluhdua.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                duapuluhdua.setText(values);
                duapuluhdua.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duapuluhduaActionPerformed

    private void duapuluhtigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhtigaActionPerformed
        // TODO add your handling code here:
         String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[22] = "x";
        }
        else
        {
            input[22] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duapuluhtiga.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                duapuluhtiga.setText(values);
                duapuluhtiga.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duapuluhtigaActionPerformed

    private void duapuluhempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhempatActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[23] = "x";
        }
        else
        {
            input[23] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duapuluhempat.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                duapuluhempat.setText(values);
                duapuluhempat.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duapuluhempatActionPerformed

    private void duapuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhlimaActionPerformed
        // TODO add your handling code here:
        String values = JOptionPane.showInputDialog("Masukkan nilai");
        if(values == null ||values.equalsIgnoreCase(""))
        {
            input[24] = "x";
        }
        else
        {
            input[24] = values;
            if(cek_sama(values)==true) 
            {
                JOptionPane.showMessageDialog(null, "Angka " + values +" sudah dimasukkan. Coba angka lain. ");
                duapuluhlima.setText("?");
                //System.out.println(values);
            } 
            else if(Integer.parseInt(values) > 30)
            {
                JOptionPane.showMessageDialog(null, "Nilai masukan maksimal 30");
            }
            else
            {   
                duapuluhlima.setText(values);
                duapuluhlima.setBackground(Color.green);
            }
        }        
    }//GEN-LAST:event_duapuluhlimaActionPerformed

    private void textbox_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_sendActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        if(!textbox_send.getText().equalsIgnoreCase(""))
        {
            try
            { 
                if(Integer.parseInt(textbox_send.getText()) <= 30)
                {
                    //System.out.println("cek if :" + textbox_send.getText());
                    System.out.println("namanya:'" + nama + "'");
                    String message="";
                    message = nama+" : "+this.textbox_send.getText();
                    try{
                        message = message;
                        clientku.broadcast(message);
                        this.textbox_send.setText("");
                    }
                    catch(Exception e){} 
                }
                else {
                    JOptionPane.showMessageDialog(null, "Nilai tebakan maksimal adalah 30");
                }
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Nilai tebakan harus diisi angka");
            }
            
        }  
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
        int a=0;
        for( a=0; a<25; a++) 
        {
            //System.out.println(input[a]);
            if(input[a].equals("x"))
            {
                
                JOptionPane.showMessageDialog(null, "Masukan belum lengkap");
                break;
            }
        }
        //System.out.print(a);
        if(a==25) 
        {
            btn_send.setEnabled(true);
            btn_play.setEnabled(false);
    
            /*
            satu.setEnabled(false);
            dua.setEnabled(false);
            tiga.setEnabled(false);
            empat.setEnabled(false);
            lima.setEnabled(false);
            enam.setEnabled(false);
            tujuh.setEnabled(false);
            delapan.setEnabled(false);
            sembilan.setEnabled(false);
            sepuluh.setEnabled(false);
            sebelas.setEnabled(false);    
            duabelas.setEnabled(false);
            tigabelas.setEnabled(false);
            empatbelas.setEnabled(false);
            limabelas.setEnabled(false);
            enambelas.setEnabled(false);
            tujuhbelas.setEnabled(false);
            delapanbelas.setEnabled(false);
            sembilanbelas.setEnabled(false);
            duapuluh.setEnabled(false);
            duapuluhsatu.setEnabled(false);
            duapuluhdua.setEnabled(false);
            duapuluhtiga.setEnabled(false);
            duapuluhempat.setEnabled(false);
            duapuluhlima.setEnabled(false);
            */
        }
    }//GEN-LAST:event_btn_playActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Integer[] inputAwal = new Integer[30];
        for(int j=1; j<=29;j++)
        {
            inputAwal[j]=j;
        }
        Collections.shuffle(Arrays.asList(inputAwal));
        System.out.println(Arrays.toString(inputAwal));
        for(int i=0; i<25; i++)
        {
            if(inputAwal[i]!=null)
                input[i] = Integer.toString(inputAwal[i]);
            else
                input[i] = Integer.toString(inputAwal[26]);
        }
        
        satu.setText(input[0]);
        satu.setBackground(Color.green);
        dua.setText(input[1]);
        dua.setBackground(Color.green);
        tiga.setText(input[2]);
        tiga.setBackground(Color.green);
        empat.setText(input[3]);
        empat.setBackground(Color.green);
        lima.setText(input[4]);
        lima.setBackground(Color.green);
        enam.setText(input[5]);
        enam.setBackground(Color.green);
        tujuh.setText(input[6]);
        tujuh.setBackground(Color.green);
        delapan.setText(input[7]);
        delapan.setBackground(Color.green);
        sembilan.setText(input[8]);
        sembilan.setBackground(Color.green);
        sepuluh.setText(input[9]);
        sepuluh.setBackground(Color.green);
        sebelas.setText(input[10]);
        sebelas.setBackground(Color.green);
        duabelas.setText(input[11]);
        duabelas.setBackground(Color.green);
        tigabelas.setText(input[12]);
        tigabelas.setBackground(Color.green);
        empatbelas.setText(input[13]);
        empatbelas.setBackground(Color.green);
        limabelas.setText(input[14]);
        limabelas.setBackground(Color.green);
        enambelas.setText(input[15]);
        enambelas.setBackground(Color.green);
        tujuhbelas.setText(input[16]);
        tujuhbelas.setBackground(Color.green);
        delapanbelas.setText(input[17]);
        delapanbelas.setBackground(Color.green);
        sembilanbelas.setText(input[18]);
        sembilanbelas.setBackground(Color.green);
        duapuluh.setText(input[19]);
        duapuluh.setBackground(Color.green);
        duapuluhsatu.setText(input[20]);
        duapuluhsatu.setBackground(Color.green);
        duapuluhdua.setText(input[21]);
        duapuluhdua.setBackground(Color.green);
        duapuluhtiga.setText(input[22]);
        duapuluhtiga.setBackground(Color.green);
        duapuluhempat.setText(input[23]);
        duapuluhempat.setBackground(Color.green);
        duapuluhlima.setText(input[24]);
        duapuluhlima.setBackground(Color.green);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_btnCloseActionPerformed

    /*cetak log file client*/
    private void btnCetakLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLogActionPerformed
        // TODO add your handling code here:
        String text, judul;
        String[] text2;
        text = txt_log.getText();
        text2 = text.split("\n");
        System.out.println("panjangnya" + text2.length);     
        File log = new File(this.nama + ".txt");
        
        try {
            if(log.exists()==false) {
                JOptionPane.showMessageDialog(null, "Log Permainan Berhasil Disimpan");
                log.createNewFile();
            }
            
            PrintWriter out = new PrintWriter(new FileWriter(log, true));          
            out.append(getTanggal()).println();
            //out.append(text).println();
            for(int i=0; i<text2.length; i++) {
                out.append(text2[i]).println();
            }
            out.append("======================================================\n\n").println();
            
            out.close();
        } catch (IOException e) {
            System.out.println("Gagal Mencetak Log Permainan");
        }
        JOptionPane.showMessageDialog(null, "Sukses Disimpan!");
    }//GEN-LAST:event_btnCetakLogActionPerformed

    private String getTanggal() { 
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss"); 
        Date date = new Date(); 
        return dateFormat.format(date); 
    } 
    
    void writelog(String s)
    {
        this.txt_log.append(s + "\n");
    }
    
    void setUsername(String s)
    {
        this.text_username.setText(s + "\n");
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_client().setVisible(true);
            }
        });
    }
      
    public void cek()
    {
        int index = 0;
        for(int a=0; a<=24 ; a++)
        {
            if(input[a].equalsIgnoreCase(terima)) 
            {
                index = a;
                aray_isi[a] = 1;
                this.cek_menang(index);
                break;
            }
            else index = 25;            //else System.out.println(terima);
            //System.out.println(input[a]);
        }
        
        if(index == 0) satu.setBackground(Color.red);
        else if(index == 1) dua.setBackground(Color.red);
        else if(index == 2) tiga.setBackground(Color.red);
        else if(index == 3) empat.setBackground(Color.red);
        else if(index == 4) lima.setBackground(Color.red);
        else if(index == 5) enam.setBackground(Color.red);
        else if(index == 6) tujuh.setBackground(Color.red);
        else if(index == 7) delapan.setBackground(Color.red);
        else if(index == 8) sembilan.setBackground(Color.red);
        else if(index == 9) sepuluh.setBackground(Color.red);
        else if(index == 10) sebelas.setBackground(Color.red);    
        else if(index == 11) duabelas.setBackground(Color.red);
        else if(index == 12) tigabelas.setBackground(Color.red);
        else if(index == 13) empatbelas.setBackground(Color.red);
        else if(index == 14) limabelas.setBackground(Color.red);
        else if(index == 15) enambelas.setBackground(Color.red);
        else if(index == 16) tujuhbelas.setBackground(Color.red);
        else if(index == 17) delapanbelas.setBackground(Color.red);
        else if(index == 18) sembilanbelas.setBackground(Color.red);
        else if(index == 19) duapuluh.setBackground(Color.red);
        else if(index == 20) duapuluhsatu.setBackground(Color.red);
        else if(index == 21) duapuluhdua.setBackground(Color.red);
        else if(index == 22) duapuluhtiga.setBackground(Color.red);
        else if(index == 23) duapuluhempat.setBackground(Color.red);
        else if(index == 24) duapuluhlima.setBackground(Color.red);
        else ;
    }
    
    public boolean cek_sama(String s)
    {
        int counter = 0;
        for (int a=0; a<=24; a++)
        {
            if(input[a].equals(s)) counter++;
        }
        //System.out.println(counter);
      if(counter>1)  return true;
      else return false;
    }
    
    public void cek_menang(int idx)
    {
        int total_vertical=0, total_horizontal=0;
        if(idx>=0 && idx<=4)
        {
            for(int a=0; a<=4; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
            
        }
        else if(idx>=5 && idx<=9)
        {
            for(int a=5; a<=9; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        else if(idx>=10 && idx<=14)
        {
            for(int a=10; a<=14; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        else if(idx>=15 && idx<=19)
        {
            for(int a=15; a<=19; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        else if(idx>=20 && idx<=24)
        {
            for(int a=20; a<=24; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        
        if(total_horizontal<5)
        {
            for(int b=idx%5; b<=25; b=b+5)
            {
                total_vertical = total_vertical + aray_isi[b];
            }
            if(total_vertical <5) total_vertical = 0;
            else {
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        
    }
    public void berhenti()
    {
        this.btn_send.setEnabled(false);
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakLog;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton delapan;
    private javax.swing.JButton delapanbelas;
    private javax.swing.JButton dua;
    private javax.swing.JButton duabelas;
    private javax.swing.JButton duapuluh;
    private javax.swing.JButton duapuluhdua;
    private javax.swing.JButton duapuluhempat;
    private javax.swing.JButton duapuluhlima;
    private javax.swing.JButton duapuluhsatu;
    private javax.swing.JButton duapuluhtiga;
    private javax.swing.JButton empat;
    private javax.swing.JButton empatbelas;
    private javax.swing.JButton enam;
    private javax.swing.JButton enambelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lima;
    private javax.swing.JButton limabelas;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JButton satu;
    private javax.swing.JButton sebelas;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton sembilanbelas;
    private javax.swing.JButton sepuluh;
    private javax.swing.JLabel text_username;
    private javax.swing.JTextField textbox_send;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tigabelas;
    private javax.swing.JButton tujuh;
    private javax.swing.JButton tujuhbelas;
    private javax.swing.JTextArea txt_log;
    // End of variables declaration//GEN-END:variables
}
