/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

/**
 *
 * @author Fandazky23
 */


import java.awt.Color;
import java.io.*;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import java.util.*;

public class UI_clientAi extends javax.swing.JFrame implements Runnable{
    int angka_tampil=0;
    public String[] input = new String[26];
    //socketClient myClient;
    public int  temp;
    private myEchoClient clientku;
    DataInputStream in = null;
    DataOutputStream out = null;
    private String nama;
    public String terima;
    public int[] aray_isi = new int[27];
    public boolean turn=false;
    public int selesai=0;
    public Thread threadHitung;
    public int[] listTebak = new int[26];
    public ArrayList<String> calonDitebak = new ArrayList<String>();
    public ArrayList<String> sudahDitebak = new ArrayList<String>();
    public ArrayList<node> calonditebak = new ArrayList<node>();
    public ArrayList<node> sudahditebak = new ArrayList<node>();
    public node kotak;
    
    /**
     * Creates new form UI
     */
    public UI_clientAi(InetAddress ip) {
        initComponents();
        
        this.nama = "Computer";
        clientku = new myEchoClient(this, ip, 1234, nama);
        clientku.makeClient();
    }
    public UI_clientAi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        sepuluh = new javax.swing.JButton();
        sebelas = new javax.swing.JButton();
        duabelas = new javax.swing.JButton();
        tigabelas = new javax.swing.JButton();
        empatbelas = new javax.swing.JButton();
        limabelas = new javax.swing.JButton();
        enambelas = new javax.swing.JButton();
        tujuhbelas = new javax.swing.JButton();
        delapanbelas = new javax.swing.JButton();
        sembilanbelas = new javax.swing.JButton();
        duapuluh = new javax.swing.JButton();
        duapuluhsatu = new javax.swing.JButton();
        duapuluhdua = new javax.swing.JButton();
        duapuluhtiga = new javax.swing.JButton();
        duapuluhempat = new javax.swing.JButton();
        duapuluhlima = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_log = new javax.swing.JTextArea();
        textbox_send = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        satu.setText("?");
        satu.setPreferredSize(new java.awt.Dimension(45, 45));
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });

        dua.setText("?");
        dua.setPreferredSize(new java.awt.Dimension(45, 45));
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });

        lima.setText("?");
        lima.setPreferredSize(new java.awt.Dimension(45, 45));
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });

        tiga.setText("?");
        tiga.setPreferredSize(new java.awt.Dimension(45, 45));
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });

        empat.setText("?");
        empat.setPreferredSize(new java.awt.Dimension(45, 45));
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });

        enam.setText("?");
        enam.setPreferredSize(new java.awt.Dimension(45, 45));
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });

        tujuh.setText("?");
        tujuh.setPreferredSize(new java.awt.Dimension(45, 45));
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });

        delapan.setText("?");
        delapan.setPreferredSize(new java.awt.Dimension(45, 45));
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });

        sembilan.setText("?");
        sembilan.setPreferredSize(new java.awt.Dimension(45, 45));
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });

        sepuluh.setText("?");
        sepuluh.setPreferredSize(new java.awt.Dimension(45, 45));
        sepuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepuluhActionPerformed(evt);
            }
        });

        sebelas.setText("?");
        sebelas.setPreferredSize(new java.awt.Dimension(45, 45));
        sebelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebelasActionPerformed(evt);
            }
        });

        duabelas.setText("?");
        duabelas.setPreferredSize(new java.awt.Dimension(45, 45));
        duabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duabelasActionPerformed(evt);
            }
        });

        tigabelas.setText("?");
        tigabelas.setPreferredSize(new java.awt.Dimension(45, 45));
        tigabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigabelasActionPerformed(evt);
            }
        });

        empatbelas.setText("?");
        empatbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        empatbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatbelasActionPerformed(evt);
            }
        });

        limabelas.setText("?");
        limabelas.setPreferredSize(new java.awt.Dimension(45, 45));
        limabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limabelasActionPerformed(evt);
            }
        });

        enambelas.setText("?");
        enambelas.setPreferredSize(new java.awt.Dimension(45, 45));
        enambelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enambelasActionPerformed(evt);
            }
        });

        tujuhbelas.setText("?");
        tujuhbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        tujuhbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhbelasActionPerformed(evt);
            }
        });

        delapanbelas.setText("?");
        delapanbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        delapanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanbelasActionPerformed(evt);
            }
        });

        sembilanbelas.setText("?");
        sembilanbelas.setPreferredSize(new java.awt.Dimension(45, 45));
        sembilanbelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanbelasActionPerformed(evt);
            }
        });

        duapuluh.setText("?");
        duapuluh.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhActionPerformed(evt);
            }
        });

        duapuluhsatu.setText("?");
        duapuluhsatu.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhsatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhsatuActionPerformed(evt);
            }
        });

        duapuluhdua.setText("?");
        duapuluhdua.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhduaActionPerformed(evt);
            }
        });

        duapuluhtiga.setText("?");
        duapuluhtiga.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhtiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhtigaActionPerformed(evt);
            }
        });

        duapuluhempat.setText("?");
        duapuluhempat.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhempatActionPerformed(evt);
            }
        });

        duapuluhlima.setText("?");
        duapuluhlima.setPreferredSize(new java.awt.Dimension(45, 45));
        duapuluhlima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duapuluhlimaActionPerformed(evt);
            }
        });

        txt_log.setColumns(20);
        txt_log.setRows(5);
        jScrollPane1.setViewportView(txt_log);

        textbox_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_sendActionPerformed(evt);
            }
        });

        btn_send.setText("Tebak");
        btn_send.setEnabled(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Bingo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textbox_send, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(sebelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(duabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(tigabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(empatbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enambelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tujuhbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(delapanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sembilanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(duapuluhsatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(duapuluhdua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(duapuluhtiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(duapuluhempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(limabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(duapuluh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(duapuluhlima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sepuluh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delapan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lima, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(sepuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sebelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tigabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empatbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enambelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tujuhbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delapanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sembilanbelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(duapuluhsatu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duapuluhdua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duapuluhtiga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duapuluhempat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(limabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(duapuluh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(duapuluhlima, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textbox_send)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
 
    }//GEN-LAST:event_satuActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
              
    }//GEN-LAST:event_enamActionPerformed

    private void sebelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebelasActionPerformed
               
    }//GEN-LAST:event_sebelasActionPerformed

    private void enambelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enambelasActionPerformed
               
    }//GEN-LAST:event_enambelasActionPerformed

    private void duapuluhsatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhsatuActionPerformed
                
    }//GEN-LAST:event_duapuluhsatuActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
     
    }//GEN-LAST:event_duaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
      
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        
    }//GEN-LAST:event_empatActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        
    }//GEN-LAST:event_limaActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
               
    }//GEN-LAST:event_delapanActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        
    }//GEN-LAST:event_sembilanActionPerformed

    private void sepuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepuluhActionPerformed
               
    }//GEN-LAST:event_sepuluhActionPerformed

    private void duabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duabelasActionPerformed
               
    }//GEN-LAST:event_duabelasActionPerformed

    private void tigabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigabelasActionPerformed
                
    }//GEN-LAST:event_tigabelasActionPerformed

    private void empatbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatbelasActionPerformed
               
    }//GEN-LAST:event_empatbelasActionPerformed

    private void limabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limabelasActionPerformed
               
    }//GEN-LAST:event_limabelasActionPerformed

    private void tujuhbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhbelasActionPerformed
                
    }//GEN-LAST:event_tujuhbelasActionPerformed

    private void delapanbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanbelasActionPerformed
                
    }//GEN-LAST:event_delapanbelasActionPerformed

    private void sembilanbelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanbelasActionPerformed
              
    }//GEN-LAST:event_sembilanbelasActionPerformed

    private void duapuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhActionPerformed
               
    }//GEN-LAST:event_duapuluhActionPerformed

    private void duapuluhduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhduaActionPerformed
                
    }//GEN-LAST:event_duapuluhduaActionPerformed

    private void duapuluhtigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhtigaActionPerformed
              
    }//GEN-LAST:event_duapuluhtigaActionPerformed

    private void duapuluhempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhempatActionPerformed
               
    }//GEN-LAST:event_duapuluhempatActionPerformed

    private void duapuluhlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duapuluhlimaActionPerformed
                
    }//GEN-LAST:event_duapuluhlimaActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        
        if(Integer.parseInt(textbox_send.getText()) <= 30)
        {
            String message="";
            message = nama+" : "+this.textbox_send.getText();
            try{
                message = message;
                clientku.broadcast(message);
                this.textbox_send.setText("");
            }
            catch(Exception e){} 
        }
        else {
            JOptionPane.showMessageDialog(null, "Nilai tebakan maksimal adalah 30");
        }  
        
    }//GEN-LAST:event_btn_sendActionPerformed

    private void textbox_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_sendActionPerformed

    public void removeTebakan(String tebakan){
        for(node tebak:calonditebak){
            if(tebak.value.equals(tebakan)){
                calonditebak.remove(tebak);
            }
        }
    }
    void writelog(String s)
    {
        this.txt_log.append(s + "\n");
        if(cek_pjg_pesan(s)==3)
        {

            kotak = new node(cek_indek_tebakan(cek_tebakan(s)), cek_tebakan(s));
            Iterator<node> it = calonditebak.iterator();
            while (it.hasNext()) {
                node kotak = it.next();
                if(kotak.getValue().equals(cek_tebakan(s)))
                {
                    it.remove();
                    sudahditebak.add(kotak);
                }
            }
            
            
            /*
            try{
                sudahditebak.add(kotak);
                //removeTebakan(cek_tebakan(s));
                //calonditebak.remove(calonditebak.indexOf(kotak));
            }
            catch(ArrayIndexOutOfBoundsException e){}
            */
            sudahDitebak.add(cek_tebakan(s));
            calonDitebak.remove(cek_tebakan(s));
            if(!cek_turn(s).equalsIgnoreCase(this.nama))
                turn = true;              
        }
        System.out.print("calon ditebak :");
        for(int i=0;i<calonditebak.size();i++)
        {
            System.out.print(calonditebak.get(i).getValue()+ " ");
        }
        System.out.println("\n");
        //System.out.println("sudah ditebak :" + sudahditebak);
        
        
    }
    int cek_pjg_pesan(String msg)
    {
        String pecah[];
        pecah = msg.split(" ");
        return pecah.length;
    }
    
    String cek_turn(String s)
    {
        String pecah[];
        pecah = s.split(" ");
        return pecah[0];
    }
    
    String cek_tebakan(String s)
    {
        String tebakan[];
        tebakan = s.split(" ");
        return tebakan[2];
    }
    int cek_indek_tebakan(String s)
    {
        int indek=-1;
        for(int i=0;i<25;i++)
        {            
            if(s.equalsIgnoreCase(input[i]))
            {
                indek = i;
                break;
            }
        }
        return indek;
    }
    /**
     * @param args the command line arguments
     */
    public void main() {
   
        System.out.println("saya AI\n");
        Integer[] inputAwal = new Integer[30];
        for(int j=1; j<=29;j++)
        {
            inputAwal[j]=j;
        }
        Collections.shuffle(Arrays.asList(inputAwal));
        System.out.println(Arrays.toString(inputAwal));
        for(int i=0; i<25; i++)
        {
            //System.out.println("mlebu for\n");
            if(inputAwal[i]!=null)
            {
                input[i] = Integer.toString(inputAwal[i]);
                kotak = new node(i, Integer.toString(inputAwal[i]));
                calonditebak.add(kotak);
                calonDitebak.add(Integer.toString(inputAwal[i]));
                //listTebak[i] = inputAwal[i];
            }                
            else
            {
                input[i] = Integer.toString(inputAwal[25]);
                kotak = new node(i, Integer.toString(inputAwal[25]));
                calonditebak.add(kotak);
                calonDitebak.add(Integer.toString(inputAwal[25]));
                //listTebak[i] = inputAwal[0];
            }
                
            
            aray_isi[i] =0;
        }
        aray_isi[25] = 0;

        satu.setText(input[0]);
        satu.setBackground(Color.green);
        dua.setText(input[1]);
        dua.setBackground(Color.green);
        tiga.setText(input[2]);
        tiga.setBackground(Color.green);
        empat.setText(input[3]);
        empat.setBackground(Color.green);
        lima.setText(input[4]);
        lima.setBackground(Color.green);
        enam.setText(input[5]);
        enam.setBackground(Color.green);
        tujuh.setText(input[6]);
        tujuh.setBackground(Color.green);
        delapan.setText(input[7]);
        delapan.setBackground(Color.green);
        sembilan.setText(input[8]);
        sembilan.setBackground(Color.green);
        sepuluh.setText(input[9]);
        sepuluh.setBackground(Color.green);
        sebelas.setText(input[10]);
        sebelas.setBackground(Color.green);
        duabelas.setText(input[11]);
        duabelas.setBackground(Color.green);
        tigabelas.setText(input[12]);
        tigabelas.setBackground(Color.green);
        empatbelas.setText(input[13]);
        empatbelas.setBackground(Color.green);
        limabelas.setText(input[14]);
        limabelas.setBackground(Color.green);
        enambelas.setText(input[15]);
        enambelas.setBackground(Color.green);
        tujuhbelas.setText(input[16]);
        tujuhbelas.setBackground(Color.green);
        delapanbelas.setText(input[17]);
        delapanbelas.setBackground(Color.green);
        sembilanbelas.setText(input[18]);
        sembilanbelas.setBackground(Color.green);
        duapuluh.setText(input[19]);
        duapuluh.setBackground(Color.green);
        duapuluhsatu.setText(input[20]);
        duapuluhsatu.setBackground(Color.green);
        duapuluhdua.setText(input[21]);
        duapuluhdua.setBackground(Color.green);
        duapuluhtiga.setText(input[22]);
        duapuluhtiga.setBackground(Color.green);
        duapuluhempat.setText(input[23]);
        duapuluhempat.setBackground(Color.green);
        duapuluhlima.setText(input[24]);
        duapuluhlima.setBackground(Color.green);
        
        threadHitung = new Thread(this);
        threadHitung.start();
    }
    
    
    public void cek()
    {
        int index = 0;
        for(int a=0; a<25 ; a++)
        {
            if(input[a].equalsIgnoreCase(terima)) 
            {
                index = a;
                aray_isi[a] = 1;
                this.cek_menang(index);
                break;
            }
            else index = 25;            //else System.out.println(terima);
            //System.out.println(input[a]);
        }
        
        if(index == 0) satu.setBackground(Color.red);
        else if(index == 1) dua.setBackground(Color.red);
        else if(index == 2) tiga.setBackground(Color.red);
        else if(index == 3) empat.setBackground(Color.red);
        else if(index == 4) lima.setBackground(Color.red);
        else if(index == 5) enam.setBackground(Color.red);
        else if(index == 6) tujuh.setBackground(Color.red);
        else if(index == 7) delapan.setBackground(Color.red);
        else if(index == 8) sembilan.setBackground(Color.red);
        else if(index == 9) sepuluh.setBackground(Color.red);
        else if(index == 10) sebelas.setBackground(Color.red);    
        else if(index == 11) duabelas.setBackground(Color.red);
        else if(index == 12) tigabelas.setBackground(Color.red);
        else if(index == 13) empatbelas.setBackground(Color.red);
        else if(index == 14) limabelas.setBackground(Color.red);
        else if(index == 15) enambelas.setBackground(Color.red);
        else if(index == 16) tujuhbelas.setBackground(Color.red);
        else if(index == 17) delapanbelas.setBackground(Color.red);
        else if(index == 18) sembilanbelas.setBackground(Color.red);
        else if(index == 19) duapuluh.setBackground(Color.red);
        else if(index == 20) duapuluhsatu.setBackground(Color.red);
        else if(index == 21) duapuluhdua.setBackground(Color.red);
        else if(index == 22) duapuluhtiga.setBackground(Color.red);
        else if(index == 23) duapuluhempat.setBackground(Color.red);
        else if(index == 24) duapuluhlima.setBackground(Color.red);
        else ;
    }
    
    public boolean cek_sama(String s)
    {
        int counter = 0;
        for (int a=1; a<=25; a++)
        {
            if(input[a].equals(s)) 
                counter++;
        }
      if(counter>1)  
          return true;
      else 
          return false;
    }
    
    public void cek_menang(int idx)
    {
        int total_vertical=0, total_horizontal=0;
        if(idx>=0 && idx<=4)
        {
            for(int a=0; a<=4; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) 
                total_horizontal =0;
            else {
                this.selesai =1;
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                    
                }
                catch(Exception e){} 
            }
            
        }
        else if(idx>=5 && idx<=9)
        {
            for(int a=5; a<=9; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) 
                total_horizontal =0;
            else {
                this.selesai =1;
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                    
                }
                catch(Exception e){} 
            }
        }
        else if(idx>=10 && idx<=14)
        {
            for(int a=10; a<=14; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                this.selesai =1;
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        else if(idx>=15 && idx<=19)
        {
            for(int a=15; a<=19; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                this.selesai =1;
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        else if(idx>=20 && idx<=24)
        {
            for(int a=20; a<=24; a++) 
            {
                total_horizontal = total_horizontal + aray_isi[a];
            }
            if(total_horizontal<5) total_horizontal =0;
            else {
                this.selesai =1;
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        
        if(total_horizontal<5)
        {
            for(int b=idx%5; b<=24; b=b+5)
            {
                total_vertical = total_vertical + aray_isi[b];
            }
            if(total_vertical <5) total_vertical = 0;
            else {
                this.selesai =1;
                String message="";
                message = nama+"#"+"kalah";
                try{
                    message = message;
                    clientku.broadcast(message);
                    this.textbox_send.setText("");
                }
                catch(Exception e){} 
            }
        }
        
    }
    public void berhenti()
    {
        this.btn_send.setEnabled(false);
    }
    
    public int jarakTerjauh()
    {
        int[] jarak = new int[26];
        Arrays.fill(jarak, 0);
        int jarakMax = 0;
        int idxMax = -1;
        for(int i=0;i<calonditebak.size();i++)
        {
             for(int j=0;j<sudahditebak.size();j++)
             {
                 jarak[i] = jarak[i] + Math.abs(sudahditebak.get(j).getIndek()%5-calonditebak.get(i).getIndek()%5) + Math.abs(sudahditebak.get(j).getIndek()/5 - calonditebak.get(i).getIndek()/5);
                 if(Math.abs(sudahditebak.get(j).getIndek()%5-calonditebak.get(i).getIndek()%5)==0 || Math.abs(sudahditebak.get(j).getIndek()/5 - calonditebak.get(i).getIndek()/5)==0);
                 {
                    jarak[i]--;
                 }
             }
             if(jarak[i] > jarakMax)
             {
                 jarakMax = jarak[i];
                 idxMax = calonditebak.get(i).getIndek();
             }               
        }
        //System.out.println("size calon ditebak : " +calonditebak.size());       
        return idxMax;
    }
    
    //int tebakan=1;
    public void kirimTebakan()
    {        
        
        String message="";
        message = nama+" : "+ input[jarakTerjauh()];
        //message = nama+" : "+Integer.toString(tebakan);
        try{
            message = message;
            clientku.broadcast(message);
            this.textbox_send.setText("");
            
        }
        catch(Exception e){}  
        //tebakan++;
    }
    public void setSelesai()
    {
        selesai = 1;
    }
    public void run()
    {
        //System.out.println("Masuk run");
        while(true)
        {
            int a=1;
            //System.out.println();
            //System.out.println(Integer.toString(selesai) +" "+ turn);
            if(selesai ==1)
            {
                System.out.println("selesai 1");
                break;
            }
            else if (turn == true && selesai==0)
            {
                //System.out.println("sudah ditebak :" + sudahDitebak);
                //System.out.println("calon ditebak :" + calonDitebak);
                //System.out.println("selesai 0");
                kirimTebakan();
                turn = false;
            }               
        }
        System.out.println("keluar while");
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JButton delapan;
    private javax.swing.JButton delapanbelas;
    private javax.swing.JButton dua;
    private javax.swing.JButton duabelas;
    private javax.swing.JButton duapuluh;
    private javax.swing.JButton duapuluhdua;
    private javax.swing.JButton duapuluhempat;
    private javax.swing.JButton duapuluhlima;
    private javax.swing.JButton duapuluhsatu;
    private javax.swing.JButton duapuluhtiga;
    private javax.swing.JButton empat;
    private javax.swing.JButton empatbelas;
    private javax.swing.JButton enam;
    private javax.swing.JButton enambelas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lima;
    private javax.swing.JButton limabelas;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JButton satu;
    private javax.swing.JButton sebelas;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton sembilanbelas;
    private javax.swing.JButton sepuluh;
    private javax.swing.JTextField textbox_send;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tigabelas;
    private javax.swing.JButton tujuh;
    private javax.swing.JButton tujuhbelas;
    private javax.swing.JTextArea txt_log;
    // End of variables declaration//GEN-END:variables
}
